name: Python CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check Python Version
        run: python --version

      - name: List Repository Files
        run: ls -la

      - name: Check Python Version
        run: python --version

      - name: Show Current Directory
        run: pwd

      - name: List Repository Files
        run: ls -la

      - name: Run Python Script
        run: python app.py